services:
  - type: web
    name: guest-code-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /.*/ # Catch-all route
        destination: /index.html
